import type { OrganizationSettingsLabels } from './types';

export const DEFAULT_ORGANIZATION_SETTINGS_LABELS: OrganizationSettingsLabels = {
  drawerTitle: 'Settings',
  closeAriaLabel: 'Close settings',
  sectionOrganization: 'Organization',
  sectionAccount: 'Account',
  sectionNotifications: 'Notifications',
  sectionAppsBilling: 'Apps & Billing',
  orgProfile: 'Organization Profile',
  companyName: 'Company name',
  logo: 'Logo',
  industry: 'Industry',
  timezone: 'Timezone',
  teamMembers: 'Team Members',
  seatsUsed: 'Seats used',
  inviteMember: 'Invite Member',
  pendingInvites: 'Pending Invites',
  resend: 'Resend',
  cancel: 'Cancel',
  appAccess: 'App Access',
  profile: 'Profile',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  password: 'Password',
  oldPassword: 'Old password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  savePassword: 'Save Password',
  emailPreferences: 'Email Preferences',
  promotionalEmails: 'Allow promotional emails',
  promotionalEmailsHint: 'Important service and security emails may still be sent.',
  textMessaging: 'Text Messaging',
  allowTextMessaging: 'Allow text messaging',
  textMessagingHint: 'Important account and security texts may still be sent.',
  organizationPlan: 'Organization Plan',
  apps: 'Apps',
  billingActions: 'Billing Actions',
  manageBilling: 'Manage Billing',
  viewInvoices: 'View Invoices',
  manage: 'Manage',
  buy: 'Buy',
  upgrade: 'Upgrade',
  mockDataNote:
    'Account, notification preferences, and organization profile (name, logo, industry, timezone) are saved to your organization. Team, seats, invites, and billing below are not connected yet.',
  organizationPlaceholderNote:
    'Preview only — team, seats, invites, and app access are not connected to your organization yet.',
  billingPlaceholderNote:
    'Preview only — plan, apps, and billing actions are not connected to a subscription yet.',
  passwordChangeComingSoon:
    'Password changes are not available here yet. Use your sign-in flow when password reset is enabled.',
  noTeamMembersYet: 'No team members to show. Member list will appear when organization membership is connected.',
  noPendingInvitesYet: 'No pending invites.',
  noAppAccessYet: 'No app entitlements to show yet.',
  seatsNotConnected: 'Seat usage will appear when team and subscription management are connected.',
  planNotConnected: 'Organization plan details are not connected yet.',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved',
  saveFailed: 'Could not save. Try again.',
  unsavedChanges: 'Unsaved changes',
  loadingSettings: 'Loading your settings…',
  uploadLogo: 'Upload logo',
  uploadingLogo: 'Uploading…',
  saveOrganizationProfile: 'Save organization profile',
  industryCnc: 'CNC / Manufacturing',
  industryHvac: 'HVAC',
  industryPlumbing: 'Plumbing',
  industryNone: 'Not set',
  timezoneSearchPlaceholder: 'Search timezones…',
};
