import type { OrganizationSettingsLabels } from './types';

export const DEFAULT_ORGANIZATION_SETTINGS_LABELS: OrganizationSettingsLabels = {
  drawerTitle: 'Settings',
  closeAriaLabel: 'Close settings',
  settingsSearchPlaceholder: 'Search settings',
  settingsSearchNoResults: 'No matching settings',
  sectionOrganization: 'Organization',
  sectionTeamMembers: 'Team Members',
  sectionAccount: 'Account',
  sectionNotifications: 'Notifications',
  sectionAppsBilling: 'Apps & Billing',
  orgProfile: 'Organization Profile',
  legalName: 'Legal organization name',
  legalNameHint: 'Used for billing, invoices, contracts, and tax or legal records.',
  displayName: 'Display name',
  displayNameHint: 'Shown in the app (navbar, invites, and settings). Leave blank to use the legal name.',
  logo: 'Logo',
  industry: 'Industry',
  timezone: 'Timezone',
  teamMembers: 'Team Members',
  seatsUsed: 'Seats used',
  inviteMember: 'Invite Member',
  pendingInvites: 'Pending Invites',
  resend: 'Resend',
  cancel: 'Cancel',
  removeMember: 'Remove',
  removeMemberAriaLabel: 'Remove member from organization',
  editMember: 'Edit member',
  editMemberAriaLabel: 'Edit member name and email',
  appAccess: 'App Access',
  profile: 'Profile',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  password: 'Password',
  oldPassword: 'Old password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  savePassword: 'Save Password',
  emailPreferences: 'Email Preferences',
  promotionalEmails: 'Allow promotional emails',
  promotionalEmailsHint: 'Important service and security emails may still be sent.',
  textMessaging: 'Text Messaging',
  allowTextMessaging: 'Allow text messaging',
  textMessagingHint: 'Important account and security texts may still be sent.',
  organizationPlan: 'Organization Plan',
  apps: 'Apps',
  billingActions: 'Billing Actions',
  manageBilling: 'Manage Billing',
  viewInvoices: 'View Invoices',
  manage: 'Manage',
  appActiveAriaLabel: 'Active',
  buy: 'Buy',
  upgrade: 'Upgrade',
  mockDataNote:
    'Account, notification preferences, and organization profile are saved to your organization. Team, seats, and app access load from your workspace when connected. Invites can be created and canceled here; invite emails are sent automatically when configured.',
  organizationPlaceholderNote:
    'Team and invite data will appear when your organization workspace is connected.',
  billingPlaceholderNote:
    'Billing actions are not connected yet. App access and plan details reflect organization entitlements when available.',
  inviteComingSoon: 'Invite email is not available yet',
  inviteEmailSent: 'Invite email sent.',
  inviteEmailFailed:
    'Invite created, but the email could not be sent. Copy the link below to share manually.',
  sendInvite: 'Send Invite',
  cancelInvite: 'Cancel Invite',
  copyInviteLink: 'Copy Invite Link',
  inviteLinkCopied: 'Invite link copied',
  inviteLinkCopyHint:
    'An invite email was sent when possible. You can also copy this link to share manually.',
  dismissInviteLink: 'Dismiss',
  resendComingSoon: 'Resend is not available yet',
  role: 'Role',
  passwordChangeComingSoon:
    'Password changes are not available here yet. Use your sign-in flow when password reset is enabled.',
  noTeamMembersYet: 'No team members to show. Member list will appear when organization membership is connected.',
  teamMembersSearchPlaceholder: 'Search by name, email, or role',
  teamMembersFilterAll: 'All',
  teamMembersNoSearchResults: 'No team members match your search.',
  noPendingInvitesYet: 'No pending invites.',
  noAppAccessYet: 'No app entitlements to show yet.',
  seatsNotConnected: 'Seat usage will appear when team and subscription management are connected.',
  planNotConnected: 'Organization plan details are not connected yet.',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved',
  saveFailed: 'Could not save. Try again.',
  unsavedChanges: 'Unsaved changes',
  loadingSettings: 'Loading your settings…',
  uploadLogo: 'Upload logo',
  uploadingLogo: 'Uploading…',
  saveOrganizationProfile: 'Save organization profile',
  industryCnc: 'CNC / Manufacturing',
  industryHvac: 'HVAC',
  industryPlumbing: 'Plumbing',
  industryNone: 'Not set',
  timezoneSearchPlaceholder: 'Search timezones…',
};
