import type { OrganizationSettingsLabels } from './types';

export const DEFAULT_ORGANIZATION_SETTINGS_LABELS: OrganizationSettingsLabels = {
  drawerTitle: 'Settings',
  closeAriaLabel: 'Close settings',
  sectionOrganization: 'Organization',
  sectionAccount: 'Account',
  sectionNotifications: 'Notifications',
  sectionAppsBilling: 'Apps & Billing',
  orgProfile: 'Organization Profile',
  companyName: 'Company name',
  logo: 'Logo',
  industry: 'Industry',
  timezone: 'Timezone',
  teamMembers: 'Team Members',
  seatsUsed: 'Seats used',
  inviteMember: 'Invite Member',
  pendingInvites: 'Pending Invites',
  resend: 'Resend',
  cancel: 'Cancel',
  appAccess: 'App Access',
  profile: 'Profile',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  password: 'Password',
  oldPassword: 'Old password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  savePassword: 'Save Password',
  emailPreferences: 'Email Preferences',
  promotionalEmails: 'Allow promotional emails',
  promotionalEmailsHint: 'Important service and security emails may still be sent.',
  textMessaging: 'Text Messaging',
  allowTextMessaging: 'Allow text messaging',
  textMessagingHint: 'Important account and security texts may still be sent.',
  organizationPlan: 'Organization Plan',
  apps: 'Apps',
  billingActions: 'Billing Actions',
  manageBilling: 'Manage Billing',
  viewInvoices: 'View Invoices',
  manage: 'Manage',
  buy: 'Buy',
  upgrade: 'Upgrade',
  mockDataNote:
    'Some fields use sample data until organization membership, invites, and billing APIs are connected.',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved',
  saveFailed: 'Could not save. Try again.',
  unsavedChanges: 'Unsaved changes',
  loadingSettings: 'Loading your settings…',
};
