import type { ZenformedNotification } from './types';

/** Demo fixtures — not production records. */
export const ZENFORMED_NOTIFICATION_FIXTURES = {
  buildcoreUnread: {
    id: 'fix-buildcore-unread',
    appSlug: 'buildcore',
    type: 'workflow_task.assigned',
    title: 'Task assigned',
    body: 'Julie Smith assigned you to Final Inspection in Unit 24.',
    destinationUrl: '/projects/unit-24/tasks',
    actorUserId: 'actor-1',
    entityType: 'workflow_task',
    entityId: 'task-1',
    metadata: { projectName: 'Unit 24' },
    readAt: null,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  buildcoreRead: {
    id: 'fix-buildcore-read',
    appSlug: 'buildcore',
    type: 'workflow_task.completed',
    title: 'Task completed',
    body: 'Final Inspection was marked complete.',
    destinationUrl: '/projects/unit-24/tasks',
    actorUserId: 'actor-1',
    entityType: 'workflow_task',
    entityId: 'task-2',
    metadata: {},
    readAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  platformUnread: {
    id: 'fix-platform-unread',
    appSlug: 'platform',
    type: 'organization.invite.accepted',
    title: 'Invite accepted',
    body: 'Alex joined your organization.',
    destinationUrl: '/settings/workspace',
    actorUserId: null,
    entityType: 'organization_invite',
    entityId: 'invite-1',
    metadata: {},
    readAt: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  noDestination: {
    id: 'fix-no-destination',
    appSlug: 'forgecore',
    type: 'system.notice',
    title: 'Maintenance window',
    body: 'ForgeCore will be briefly unavailable tonight.',
    destinationUrl: null,
    actorUserId: null,
    entityType: null,
    entityId: null,
    metadata: {},
    readAt: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  longCopy: {
    id: 'fix-long-copy',
    appSlug: 'buildcore',
    type: 'workflow_task.assigned',
    title:
      'A very long notification title that should wrap gracefully without breaking the dropdown layout',
    body: 'BuildCore — This is an intentionally long body that begins with a redundant app prefix and then continues with plenty of detail about assignment context across multiple wrapping lines.',
    destinationUrl: '/projects/long/tasks',
    actorUserId: 'actor-2',
    entityType: 'workflow_task',
    entityId: 'task-long',
    metadata: {},
    readAt: null,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  unknownApp: {
    id: 'fix-unknown-app',
    appSlug: 'future_app',
    type: 'custom.event',
    title: 'Custom event',
    body: 'From an app that is not yet in the icon catalog.',
    destinationUrl: '/somewhere',
    actorUserId: null,
    entityType: null,
    entityId: null,
    metadata: {},
    readAt: null,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
} as const satisfies Record<string, ZenformedNotification>;

export const ZENFORMED_NOTIFICATION_FIXTURE_LIST: readonly ZenformedNotification[] = [
  ZENFORMED_NOTIFICATION_FIXTURES.buildcoreUnread,
  ZENFORMED_NOTIFICATION_FIXTURES.platformUnread,
  ZENFORMED_NOTIFICATION_FIXTURES.buildcoreRead,
  ZENFORMED_NOTIFICATION_FIXTURES.noDestination,
  ZENFORMED_NOTIFICATION_FIXTURES.longCopy,
  ZENFORMED_NOTIFICATION_FIXTURES.unknownApp,
];
