declare const classes: {
  readonly dot: string;
  readonly dotOnline: string;
  readonly dotAway: string;
  readonly dotBusy: string;
  readonly dotOffline: string;
  readonly avatarWithDot: string;
  readonly avatarDot: string;
  readonly statusSelector: string;
  readonly statusTrigger: string;
  readonly statusTriggerMain: string;
  readonly statusTriggerChevron: string;
  readonly statusMenu: string;
  readonly statusOption: string;
  readonly statusOptionMain: string;
  readonly statusOptionSelected: string;
  readonly statusOptionLabel: string;
  readonly statusOptionCheck: string;
};
export default classes;
